# Generated by Django 4.1.5 on 2023-02-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0002_alter_fruit_exist_alter_fruit_name_alter_fruit_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fruit',
            options={'verbose_name': 'Фрукт', 'verbose_name_plural': 'Фрукты'},
        ),
        migrations.AddField(
            model_name='fruit',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='fruit',
            name='date_create',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='fruit',
            name='date_expired',
            field=models.DateField(null=True, verbose_name='Срок годности'),
        ),
        migrations.AlterField(
            model_name='fruit',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='fruit',
            name='exist',
            field=models.BooleanField(default=True, verbose_name='В каталоге?'),
        ),
        migrations.AlterField(
            model_name='fruit',
            name='name',
            field=models.CharField(default='fruit', max_length=120, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='fruit',
            name='photo',
            field=models.ImageField(null=True, upload_to='image/%Y/%m/%d', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='fruit',
            name='price',
            field=models.FloatField(default=10, verbose_name='Цена'),
        ),
    ]
