# Generated by Django 4.1.5 on 2023-02-19 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0004_supplier_fruit_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')),
                ('date_finish', models.DateTimeField(null=True, verbose_name='Дата завершения заказа')),
                ('price', models.FloatField(null=True, verbose_name='Стоимость заказа')),
                ('address_delivery', models.CharField(max_length=150, verbose_name='Адрес доставки')),
                ('status', models.CharField(choices=[(1, 'Создан'), (2, 'Отменён'), (3, 'Согласован'), (4, 'В пути'), (5, 'Завершён')], max_length=150, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['date_create'],
            },
        ),
        migrations.AlterField(
            model_name='fruit',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='fruit.supplier', verbose_name='Поставщик'),
        ),
        migrations.CreateModel(
            name='Pos_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_fruit', models.IntegerField(verbose_name='Количество фруктов')),
                ('price', models.FloatField(verbose_name='Общая цена фруктов')),
                ('fruit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fruit.fruit', verbose_name='Фрукт')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fruit.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Позиция',
                'verbose_name_plural': 'Позиции',
                'ordering': ['fruit', 'order', 'price'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='fruits',
            field=models.ManyToManyField(through='fruit.Pos_order', to='fruit.fruit'),
        ),
    ]
