# Generated by Django 4.1.5 on 2023-02-23 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0006_chegue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chegue',
            options={'ordering': ['terminal', 'date_print'], 'verbose_name': 'Чек', 'verbose_name_plural': 'Чеки'},
        ),
    ]
